name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get next version
        id: version
        uses: reecetech/version-increment@2024.4.3
        with:
          scheme: semver
          increment: patch  # Увеличивает патч-версию (например, с 1.0.0 на 1.0.1)

      - name: Set image tag
        id: tag
        run: |
          echo "IMAGE_TAG=championsleague12/actions-busybox:${{ steps.version.outputs.version }}" >> $GITHUB_ENV

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: championsleague12/actions-busybox
          tags: |
            type=semver,pattern={{version}}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
