name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        IMAGE_TAG="championsleague12/actions-busybox:${GITHUB_SHA::7}"
        docker build -f ../Dockerfile --tag $IMAGE_TAG
    - name: Docker Login
      uses: docker/login-action@v3.4.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push Docker image
      run: |
        docker push $IMAGE_TAG
